### ISSUE TITLE
Error "LineColorMap_regex not valid"

### ISSUE THREAD

**Issue by Siggylicious** [Newborg/ColorTerminal#4]
Error "LineColorMap_regex not valid" stays if regex values goes from identical to different. 
It is not possible so save, even though all regex values are different.

Seen in origin/master commit 04bdfbc3c3c24fb0d45e8f2096bf5e36362f53ac [04bdfbc]

Can be bypassed if the highlighted regex is changed to something else and then back again.

![colorterminallineregexcolorbug](https://user-images.githubusercontent.com/8341952/50822595-6082fb00-1332-11e9-98f7-5dca9dca29cc.png)

**Comment by Newborg** [comment]
Better entry validation tracking added. Issue fixed
