### ISSUE TITLE
Ascii ACK/NAK not supported, or what is causing this?

### ISSUE THREAD

**Issue by Siggylicious** [Newborg/ColorTerminal#6]
The square symbols seen below should be ascii ACKs

![colorterminalacknotsupported](https://user-images.githubusercontent.com/8341952/51592574-429bc580-1ef0-11e9-8e83-afad548543e8.gif)

Do you know what might be causing this behavior?

Spacing seems to get bigger and bigger moving cursor over text from left to right, see GIF above.

**Comment by Newborg** [comment]
Seems to be a problem with the tkinter text widget trying to render non-printable ascii
